### ISSUE TITLE
highway=track n'apparait pas

### ISSUE THREAD

**Issue by ponyodc** [Louis-LJ/OsmAnd_Hiking_Map#12]
Bonjour, 
Tout d'abord merci beaucoup pour ce xml que j'utilise depuis bien 2 ans maintenant, je le trouve vraiment super ! 

Petit problème néanmoins lors de ma dernière rando, un sentier marqué comme "Track / Land-access road" (https://wiki.openstreetmap.org/wiki/Tag:highway=track) ne s'affichait pas, bien que présent. 

Je remarque effectivement qu'il n'est pas défini dans le xml. Est-ce un oubli ? Il y a t-il une autre manière d'afficher ces "track" qui sont parfois des chemins de rando ? 

Merci encore !

**Comment by Louis-LJ** [comment]
Bonjour, 
est-ce que le track en question est identifié sur OSM ?

Sachez que la nouvelle adresse pour le rendu à jour est à cette adresse https://github.com/OsmAnd-Rendering/Hiking

**Comment by ponyodc** [comment]
Bonjour, 

Je viens de télécharger la version de la page fournie et de tester, le même problème apparait. Certains trails n'apparaissent pas. 
Exemple avec les deux screenshots joints pour le même lieu : 1 réalisé avec le profil "topo" de OSMand et l'autre avec le profil "randonnée". 

![Profil randonnee](https://github.com/Louis-LJ/OsmAnd_Hiking_Map/assets/76070387/60b15957-81f6-4194-935f-94c7a49ea62b)
![Profil topo](https://github.com/Louis-LJ/OsmAnd_Hiking_Map/assets/76070387/5ba40d20-c925-4a87-a14b-374eb5e292db)

C'est bizarre...

**Comment by Louis-LJ** [comment]
Vous avez "tué" l'application puis relancé ? 

Les hihgway=track sont dans le rendu. Vous avez téléchargé le xml ou le fichier avec les profils ? 

J'ai supprimé le rendu "hiking" et réinstallé avec les profils et ça fonctionne bien de mon côté. 


![image](https://github.com/Louis-LJ/OsmAnd_Hiking_Map/assets/79785663/507487cb-b6cd-4981-ad9f-1ee5f03d6b1f)

**Comment by ponyodc** [comment]
Effectivement, ca venait d'un problème d'installation de mon côté. J'avais des fichiers xml "hiking" et "randonnée" ce qui a du embrouiller OSMand. J'ai supprimé ces deux fichiers et réinjecté le fichier hiking.osf, tout fonctionne maintenant. 

Merci pour ton aide !
